server:
  port: 8090

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #jpa:
  #  database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  hibernate:
  #    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telran
    username: postgres
    password: root

logging:
  loggingXml: false
  file:
    name: hello-spring-boot.log
