name: Build and Push Docker Image

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case repo name
        run: echo "REPO_NAME_LC=${REPO_NAME,,}" >> $GITHUB_ENV
        env:
          REPO_NAME: '${{ github.repository }}'

      - name: Build Docker image and push to GitHub Container Registry
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: user-profile-app/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME_LC }}/user-profile-service:latest